name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npx hardhat compile
      - run: npx hardhat test test/PropertyEscrow.test.js test/EscrowFactory.test.js test/Integration.test.js test/EscrowFactoryUpgradeable.fixed.test.js
      - run: npx hardhat coverage --testfiles "test/PropertyEscrow.test.js,test/EscrowFactory.test.js,test/Integration.test.js,test/EscrowFactoryUpgradeable.fixed.test.js"
      - run: npx solhint "contracts/**/*.sol" --max-warnings 100